### PR TITLE
support for local cache

### PR DESCRIPTION
**Pull request by deitch**
Provides support for optional local caching of `.apk` and `APKINDEX.tar.gz` files.

Can choose whether to do:

* no cache (default)
* cache in a user-provided directory
* cache in system-default directory

Under the directory is a directory for each remote repository, as well as one for each architecture. This is described in `CACHE.md`.

Tests added, of course.

In terms of cache expiration, along with the `APKINDEX.tar.gz` files and the `*.apk` files, we store a file with the same name that ends in `.etag`. If the fetch from the remote includes an `etag` header, it saves it. In future calls, it first calls `HEAD` to see if the etag matches, and only then retrieve if it differs.

What happens if there is no etag? This, too, is controllable, and differs by type of file:

* `APKINDEX.tar.gz`: because this file is not versioned at all, no etag means treat every requests as new. Only use the cache if **both** of the following are true: we have an etag, it matches the etag on the next `HEAD` call.
* `*.apk` files: because these files are versioned, we can be a little more relaxed. If the cache file has an etag and the remote has an etag, check them, and update the cache if they differ. If there is no local etag or no remote etag, then treat the local versioned file as up to date.

Of course, docs and tests on all of the above.

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
Haven't had a chance to fully review this yet, but reading the PR description:

Would it ever make sense to respect Cache-Control headers, too? Or do we want to err on the side of always being up to date?

Don't we have checksums and/or signatures for the APKs? Can we take advantage of that?

**Comment by deitch** [comment]
Added some safety checks in `cachePathFromURL()`, which should be enough to let codeql pass it. If not, it is a codeql error.

**Comment by deitch** [comment]
Excellent, codeql is happy now.

**Comment by deitch** [comment]
@jonjohnsonjr also, I would be up for improvements of the caching algorithm, whether during this PR or after as a follow-on

**Review by jonjohnsonjr — APPROVED** [review]

**Pull request merged**
