### PR TITLE
Fix Replaces

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
This should have been a []string but was a string.

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
Converting to draft because these don't belong in the APKINDEX _at all_, apparently 🤔

**Comment by jonjohnsonjr** [comment]
Alright let's stop writing these lines to APKINDEX but not yet write them to the installed db because I want to fix being able to build these things before I have to deal with the non-reproducibility stuff everywhere.

**Comment by imjasonh** [comment]
F'ing automerge 😅

**Comment by kaniini** [comment]
looks ok to me :)

**Pull request merged**
