### PR TITLE
Atomically write APKs into the cache

### PR DESCRIPTION
**Pull request by mattmoor**
The current caching implementation is effectively unusable when multiple concurrent `apko` builds are performed using the same caching directory because the cache is not populated atomically.

The cache file is created (at which point `os.Stat` will report a cache hit), and then it is populated and only closed via `defer` so not until the `retrieveAndSave` function returns!  When used with the `tf-apko` provider downstream I see loads of errors like this when it's used to perform concurrent builds:
```
│ failed to build layer image for "arm64": installing apk packages: unable to
│ expand apk for package glibc: expandApk error 3: unexpected EOF
```

This change has a few parts:
1. Download the APK into a temporary file, 
2. `Close()` it prior to continuing on, and
3. (once the `etag` file is optionally populated) Use `os.Rename` to atomically move the file into the cache.

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]

**Comment by deitch** [comment]
Is there a test we can add for the caching issue? Something as simple as writing in parallel? I think we already test `-race`, and if not, we can add it.

**Comment by deitch** [comment]
This should help. The original thought was that you shouldn't be running multiple instances of `go-apk` to the same filesystem at the same time. Which is correct, as far as a the _target_ of the build is concerned. As far as the _cache_ is concerned, it is completely legit. So this does fix it.

I see two issues here, minor and major:

* minor: it still could lead to conflicts. `os.Rename()` is very fast, but still not zero time.
* major: `os.Rename()` returns error if you try to do it across filesystems. For example, if your tmpdir is on one partition and cache on another, this will fail.

We had to deal with the major one before, see [this part of apko](https://github.com/chainguard-dev/go-apk/issues/63#event-9534790395), which is from [this PR](https://github.com/chainguard-dev/apko/pull/733).

Do you want to update it?

**Comment by mattmoor** [comment]
AIUI os.Rename is the standard mechanism for atomically moving a file into place in Go.The rename cannot be across devices because I am passing the cache directory as the “temp fir” to use, so it is always in the same directory.-M(obile)On Jun 15, 2023, at 12:15 AM, Avi Deitcher ***@***.***> wrote:﻿
This should help. The original thought was that you shouldn't be running multiple instances of go-apk to the same filesystem at the same time. Which is correct, as far as a the target of the build is concerned. As far as the cache is concerned, it is completely legit. So this does fix it.
I see two issues here, minor and major:

minor: it still could lead to conflicts. os.Rename() is very fast, but still not zero time.
major: os.Rename() returns error if you try to do it across filesystems. For example, if your tmpdir is on one partition and cache on another, this will fail.

We had to deal with the major one before, see this part of apko, which is from this PR.
Do you want to update it?

**Comment by deitch** [comment]
Looking again at your code, I see now that the tmpdir is _inside_ the cache dir. I didn't realize that before. I think we would be OK then.

**Pull request merged**
